---
- name: Create Policy
  na_ontap_export_policy:
    state: present
    name: "{{ policy }}"
    vserver: "{{ vserver }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
- name: Setup rules
  na_ontap_export_policy_rule:
    state: present
    policy_name: "{{ policy }}"
    vserver: "{{ vserver }}"
    client_match: 0.0.0.0/0
    ro_rule: any
    rw_rule: any
    super_user_security: any
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
- name: Create volume
  na_ontap_volume:
    state: present
    name: "{{ volname }}"
    aggregate_name: "{{ aggr }}"
    size: "{{ size }}"
    size_unit: gb
    policy: "{{ policy }}"
    junction_path: "/{{ volname }}"
    space_guarantee: "none"
    vserver: "{{ vserver }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
