---
- name: Create SVM
  na_ontap_svm:
    state: present
    name: "{{ vserver }}"
    root_volume: "{{ vserver }}_root"
    root_volume_aggregate: n1_aggr1
    root_volume_security_style: mixed
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: Create interface
  na_ontap_interface:
    state: present
    interface_name: "{{ vserver }}_mgmt_data_1"
    home_port: e0b
    home_node: Select-cluster-01
    role: data
    protocols: nfs
    admin_status: up
    is_auto_revert: true
    address: "{{ address }}"
    netmask: 255.255.255.0
    vserver: "{{ vserver }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: change nfs status
  na_ontap_nfs:
    state: present
    service_state: started
    vserver: "{{ vserver }}"
    nfsv3: enabled
    nfsv4: disabled
    nfsv41: disabled
    tcp: enabled
    udp: enabled
    vstorage_state: disabled
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"

- name: Setup default rules
  na_ontap_export_policy_rule:
    state: present
    policy_name: default
    vserver: "{{ vserver }}"
    client_match: 0.0.0.0/0
    ro_rule: any
    rw_rule: any
    super_user_security: none
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
